name: INPUT OUTPUT PROGRAM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile and Test C++ Code
     
      run: |
        g++ main.cpp student.cpp -o program
        printf "3\nno\n" | ./program
